[sdl]
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=original
output=surface
autolock=true
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-0.74.map
usescancodes=true

[config]
working directory option=noprompt

[gui]
working directory option=noprompt
quit warning=false
showsplash=false

[dosbox]
language=
machine=svga_s3
captures=capture
memsize=16

[render]
frameskip=0
aspect=false
scaler=none

[cpu]
core=normal
cputype=auto
cycles=fixed 25000
cycleup=10
cycledown=20

[mixer]
nosound=true

[midi]
mpu401=none
mididevice=none

[sblaster]
sbtype=none

[gus]
gus=false

[speaker]
pcspeaker=false
tandy=off
disney=false

[joystick]
joysticktype=none

[serial]
serial1=nullmodem transparent:1 inhsocket:1
serial2=disabled
serial3=disabled
serial4=disabled

[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto

[bios]
rows=25
columns=80

[autoexec]
MOUNT C /app/dosbox/drive
PATH Z:\;C:\doors\bin;C:\bin
C:
FAKESHAR
BNU /R16384 /T32768
BNU /L0:38400,8N1 /W0- /H0-
