[sdl]
fullscreen=false
fulldouble=false
output=surface
priority=higher,normal

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=normal
cputype=auto
cycles=10000

[mixer]
nosound=true

[midi]
mpu401=none
mididevice=none

[sblaster]
sbtype=none

[serial]
serial1=nullmodem transparent:1 usedtr:0 telnet:0 port:19999

[autoexec]
MOUNT C /app/dosbox/drive
PATH Z:\;C:\bin;C:\doors\bin
C:
CTTY COM1
